### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by mehtaanirudh** [sassoftware/restaf-uidemos#7] opened 2021-07-30 09:32 UTC
In the install instructions the code snippet `git clone https://sassoftware/restaf-uidemos` should be changed to `git clone https://github.com/sassoftware/restaf-uidemos`

**Comment by devaKumaraswamy** [comment] 2021-07-30 11:46
@mehtaanirudh Thanks for pointing it out. Will fix it shortly. Cheers... Deva

**Comment by devaKumaraswamy** [comment] 2022-06-24 12:34
duplicate of #8

**Closed as completed by devaKumaraswamy** 2022-06-24 12:34 UTC
